/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.Philadelphia.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mx.itson.Philadelphia.persistencia.ConductorDAO;

/**
 *
 * @author pyatq
 */
public class ConductorFormulario extends javax.swing.JDialog {

    
    int id;
    String nombre;
    String numeroLicencia;
    String fechaAlta;
    SimpleDateFormat formato = new SimpleDateFormat("d 'de' MMMM 'de' yyyy");
    
    /**
     * Creates new form ConductorFormulario
     */
    public ConductorFormulario(java.awt.Frame parent, boolean modal, int id,String nombre, String numeroLicencia, String fechaAlta) {
        
        
        super(parent, modal);
        initComponents();
        
        this.id = id;
        this.nombre = nombre;
        this.numeroLicencia = numeroLicencia;
        this.fechaAlta = fechaAlta;
        cargarFormulario();
        setLocationRelativeTo(null);
        
        txtNombre.setText(nombre);
        txtNumeroLicencia.setText(numeroLicencia);
        txtFechaAlta.setText(fechaAlta);
    }

   
    public void cargarFormulario(){
        if(this.id != 0){
            //Si el ID es diferente de cero, entonces está intentando editr un registro.
            //Por tanto, se consulta el método paraa obtener un conductor por su ID y se cargan los valores en el formulario
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroLicencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaAlta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Número Licecia:");

        jLabel3.setText("Fecha de alta:");

        jLabel4.setText("Usar fecha con formato \"d 'de' MMMM 'de' yyyy\"");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroLicencia)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 200, Short.MAX_VALUE))
                    .addComponent(txtNombre)
                    .addComponent(txtFechaAlta))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombre.getText();
        String numeroLisecia = txtNumeroLicencia.getText();
        String fechaAlta = txtFechaAlta.getText();
        Date fechaConvertida = null;
        
        
        try { 
            Date parsed = formato.parse(fechaAlta);
            fechaConvertida = new java.sql.Date(parsed.getTime());
        } catch (ParseException ex) {
            System.err.println("Ocurrio un error: " + ex);
        }
        
        boolean operacion = false;
        
        if(this.id == 0 ){
        operacion = ConductorDAO.guardar(nombre, numeroLisecia, fechaConvertida);
        }else{
        ConductorDAO conductorDAO = new ConductorDAO();
        operacion = conductorDAO.editar(id, nombre, numeroLisecia, fechaConvertida);
        
        }
        
        
        
        if(operacion == true){
        JOptionPane.showMessageDialog(this, "Guardado Exitosamente","Operacion realizada", JOptionPane.INFORMATION_MESSAGE);
        
        }else{
        JOptionPane.showMessageDialog(this, "No se pudo guardar","Operacion fallida", JOptionPane.WARNING_MESSAGE);
        }
        
            this.dispose();
            ConductorListado frame = new ConductorListado();
            frame.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFechaAlta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroLicencia;
    // End of variables declaration//GEN-END:variables
}
