/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.Philadelphia.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import mx.itson.Philadelphia.entidades.Conductor;
import mx.itson.Philadelphia.entidades.Oficial;
import mx.itson.Philadelphia.persistencia.ConductorDAO;
import mx.itson.Philadelphia.persistencia.OficialDAO;
import mx.itson.philadelphia.persistencia.MultaDAO;


/**
 *
 * @author jesus
 */
public class MultaFormulario extends javax.swing.JDialog {
    
    int id;
    String folio;
    String motivo;
    String fecha;
    SimpleDateFormat formato = new SimpleDateFormat("d 'de' MMMM 'de' yyyy");
    

    /**
     * Creates new form MultaFormulario
     */
    public MultaFormulario(java.awt.Frame parent, boolean modal, int id, String folio, String motivo, String fecha) {
        super(parent, modal);
        initComponents();
        
        this.id = id;
        this.folio = folio;
        this.motivo = motivo;
        this.fecha = fecha;
        
        cargarFormulario();
        
        cargarConductores();
        
        cargarOficial();
        
        setLocationRelativeTo(null);
        
        txtFolio.setText(folio);
        txtMotivo.setText(motivo);
        txtFecha.setText(fecha);
       
    }
    
    public void cargarFormulario(){
        if(this.id != 0){
            //Si el ID es diferente de cero, entonces está intentando editr un registro.
            //Por tanto, se consulta el método paraa obtener un conductor por su ID y se cargan los valores en el formulario
            
        }
    }

    public void cargarConductores(){
        List<Conductor> conductores = ConductorDAO.obtenerTodos();
        for(Conductor c : conductores){
            cmbConductor.addItem(c);
        }
    }
    
    public void cargarOficial(){
        List<Oficial> oficiales = OficialDAO.obtenerTodos();
        for(Oficial o : oficiales){
            cmbOficial.addItem(o);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbConductor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbOficial = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Folio");

        jLabel2.setText("Motivo");

        jLabel3.setText("Conductor");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha:");

        jLabel5.setText("Usar fecha con formato \"d 'de' MMMM 'de' yyyy\"");

        jLabel6.setText("Oficial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(txtFolio)
                                    .addComponent(txtMotivo)
                                    .addComponent(cmbConductor, 0, 351, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbOficial, javax.swing.GroupLayout.Alignment.LEADING, 0, 351, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(62, 62, 62)))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cmbOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Conductor c = (Conductor)cmbConductor.getSelectedItem();
        System.out.println("El conductor selccionado es " + c.getId() + " de nombre " + c.getNombre());
        
        //
        
        Oficial o = (Oficial)cmbOficial.getSelectedItem();
        System.out.println("El conductor selccionado es " + o.getId() + " de nombre " + o.getNombre());
        
        //
        
        String folio = txtFolio.getText();
        String motivo = txtMotivo.getText();
        String fecha = txtFecha.getText();
        Date fechaConvertida = null;
        
        try { 
            Date parsed = formato.parse(fecha);
            fechaConvertida = new java.sql.Date(parsed.getTime());
        } catch (ParseException ex) {
            System.err.println("Ocurrio un error: " + ex);
        }    
        
        boolean operacion = false;
        
        if(this.id == 0 ){
        operacion = MultaDAO.guardar(folio, motivo, fechaConvertida);
                
               
        }else{
        MultaDAO multaDAO = new MultaDAO();
        operacion = multaDAO.editar(id, folio, motivo, fechaConvertida);
        }
        
        if(operacion == true){
        JOptionPane.showMessageDialog(this, "Guardado Exitosamente","Operacion realizada", JOptionPane.INFORMATION_MESSAGE);
        
        }else{
        JOptionPane.showMessageDialog(this, "No se pudo guardar","Operacion fallida", JOptionPane.WARNING_MESSAGE);
        }
        
            this.dispose();
            MultaListado frame = new MultaListado();
            frame.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Conductor> cmbConductor;
    private javax.swing.JComboBox<Oficial> cmbOficial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
